/* AUTO-GENERATED by npm run scenario:build. DO NOT EDIT. */
import type { ScenarioModule } from '../../../scenario/generated/scenario-schema';
import asset0 from '../../../../assets/scenes/客厅.png';
import asset1 from '../../../../assets/scenes/警局.png';
import asset2 from '../../../../assets/scenes/酒吧.png';
import asset3 from '../../../../assets/scenes/药店.png';
import asset4 from '../../../../assets/scenes/码头.png';
import asset5 from '../../../../assets/avatars/isabella.png';
import asset6 from '../../../../assets/avatars/eric.png';
import asset7 from '../../../../assets/avatars/montreal.png';
import asset8 from '../../../../assets/avatars/bartender.png';
import asset9 from '../../../../assets/avatars/deep_one.svg';

export const scenarioContentHash = "56bbdc8889d15bd1";
export const scenarioAssetUrls: Record<string, string> = {
  "scene.S01": asset0,
  "scene.S02": asset1,
  "scene.S03": asset2,
  "scene.S04": asset3,
  "scene.S05": asset4,
  "npc.N01": asset5,
  "npc.N02": asset6,
  "npc.N03": asset7,
  "npc.N04": asset8,
  "npc.N05": asset9
};
export const generatedScenarioModule = {
  "manifest": {
    "schemaVersion": 1,
    "contentVersion": "1.1.9",
    "id": "wuzhongxiaoshi",
    "title": "雾中消逝",
    "system": "COC 第七版风格 D100",
    "era": "1920年7月13日，英国伦敦",
    "startTime": "1920-07-13T17:30",
    "playerCount": {
      "min": 1,
      "max": 4
    },
    "expectedDurationMinutes": 180,
    "turnMinutes": 5,
    "tone": "雨雾笼罩的都市调查，逐步转向克苏鲁式海港恐怖",
    "contentWarnings": [
      "毒品走私",
      "绑架",
      "枪械暴力",
      "超自然恐怖"
    ],
    "authors": [
      "舒爾茲上尉"
    ],
    "source": "docs/GDD.md 第四章与第七章规则边界",
    "credits": [
      "AI 跑团项目组结构化改编"
    ],
    "startSceneId": "S01",
    "startBeatId": "B01",
    "assets": {
      "scene.S01": "../../assets/scenes/客厅.png",
      "scene.S02": "../../assets/scenes/警局.png",
      "scene.S03": "../../assets/scenes/酒吧.png",
      "scene.S04": "../../assets/scenes/药店.png",
      "scene.S05": "../../assets/scenes/码头.png",
      "npc.N01": "../../assets/avatars/isabella.png",
      "npc.N02": "../../assets/avatars/eric.png",
      "npc.N03": "../../assets/avatars/montreal.png",
      "npc.N04": "../../assets/avatars/bartender.png",
      "npc.N05": "../../assets/avatars/deep_one.svg"
    }
  },
  "world": {
    "facts": [
      {
        "id": "F01",
        "category": "truth",
        "scope": "dm",
        "immutable": true,
        "statement": "埃里克·摩勒参与毒品运输，并被同伙绑架在扶桑花号上。"
      },
      {
        "id": "F02",
        "category": "truth",
        "scope": "dm",
        "immutable": true,
        "statement": "洛夫·蒙特利尔与埃里克私下勾连，并会阻挠调查。"
      },
      {
        "id": "F03",
        "category": "truth",
        "scope": "dm",
        "immutable": true,
        "statement": "深潜者混种藏身卡森其药店，并计划于7月14日乘船离开。"
      },
      {
        "id": "F04",
        "category": "testimony",
        "scope": "player",
        "statement": "埃里克于7月10日失踪，警方没有取得进展。"
      },
      {
        "id": "F05",
        "category": "evidence",
        "scope": "player",
        "statement": "合影显示蒙特利尔与埃里克关系异常密切。"
      },
      {
        "id": "F06",
        "category": "evidence",
        "scope": "player",
        "statement": "小册子的隐写内容指向贝尔街14号卡森其药店。"
      },
      {
        "id": "F07",
        "category": "evidence",
        "scope": "player",
        "statement": "白色粉末经医学分析可确认是高纯度鸦片。"
      },
      {
        "id": "F08",
        "category": "testimony",
        "scope": "player",
        "statement": "老赫特酒保掌握“老鼠”线索，可提供贝尔街方向。"
      },
      {
        "id": "F09",
        "category": "evidence",
        "scope": "player",
        "statement": "地图笔记标出泰晤士港扶桑花号的停泊位置。"
      },
      {
        "id": "F10",
        "category": "evidence",
        "scope": "player",
        "statement": "雪茄头能证明埃里克近期到过卡森其药店。"
      },
      {
        "id": "F11",
        "category": "threat",
        "scope": "dm",
        "immutable": true,
        "statement": "调查员见过蒙特利尔后，晚间到贝尔街会遭遇三名暴徒。"
      },
      {
        "id": "F12",
        "category": "threat",
        "scope": "dm",
        "immutable": true,
        "statement": "扶桑花号战斗持续七轮后，深潜者会带船逃脱。"
      },
      {
        "id": "F13",
        "category": "truth",
        "scope": "dm",
        "immutable": true,
        "statement": "扶桑花号的深潜者只要求带走走私货物并安全离港；若调查员承诺不追击，他们愿意释放埃里克。"
      }
    ],
    "scenes": [
      {
        "id": "S01",
        "name": "摩勒住宅",
        "chapterTitle": "第一幕：接受委托",
        "description": "纽伦上街101-102号的维多利亚式别墅，伊莎贝拉·摩勒在此等待调查员。",
        "aliases": [
          "摩勒家",
          "住宅",
          "别墅"
        ],
        "assetId": "scene.S01",
        "npcIds": [
          "N01"
        ],
        "itemIds": [
          "I01",
          "I02",
          "I03",
          "I04",
          "I05",
          "I06"
        ],
        "dmFactIds": [
          "F01"
        ],
        "exits": [
          {
            "to": "S02",
            "travelMinutes": 10,
            "when": {
              "factKnown": "F05"
            },
            "blockedText": "目前没有足够理由直接质询警察局长。"
          },
          {
            "to": "S03",
            "travelMinutes": 10,
            "when": {
              "variable": "oldHethLead",
              "op": "eq",
              "value": true
            },
            "blockedText": "你们还不知道老赫特酒吧与此案的联系。"
          },
          {
            "to": "S04",
            "travelMinutes": 20,
            "when": {
              "any": [
                {
                  "factKnown": "F06"
                },
                {
                  "factKnown": "F08"
                }
              ]
            },
            "blockedText": "你们还没有确认贝尔街14号的具体目标。"
          }
        ]
      },
      {
        "id": "S02",
        "name": "上城区第二分局",
        "chapterTitle": "第二幕：街区调查",
        "description": "距离摩勒住宅约十分钟路程，洛夫·蒙特利尔局长在这里办公。",
        "aliases": [
          "第二分局",
          "警察局",
          "警局"
        ],
        "assetId": "scene.S02",
        "npcIds": [
          "N03"
        ],
        "itemIds": [],
        "dmFactIds": [
          "F02",
          "F11"
        ],
        "exits": [
          {
            "to": "S01",
            "travelMinutes": 10,
            "when": {
              "always": true
            },
            "blockedText": "无法返回摩勒住宅。"
          },
          {
            "to": "S03",
            "travelMinutes": 10,
            "when": {
              "variable": "oldHethLead",
              "op": "eq",
              "value": true
            },
            "blockedText": "你们还没有老赫特酒吧的线索。"
          },
          {
            "to": "S04",
            "travelMinutes": 15,
            "when": {
              "any": [
                {
                  "factKnown": "F06"
                },
                {
                  "factKnown": "F08"
                }
              ]
            },
            "blockedText": "你们还没有贝尔街14号的可靠地址。"
          }
        ]
      },
      {
        "id": "S03",
        "name": "老赫特酒吧",
        "chapterTitle": "第二幕：街区调查",
        "description": "街区内昏暗嘈杂的小酒馆，空气里弥漫着烟草和廉价酒气。",
        "aliases": [
          "老赫特之家",
          "酒吧"
        ],
        "assetId": "scene.S03",
        "npcIds": [
          "N04"
        ],
        "itemIds": [],
        "dmFactIds": [
          "F08"
        ],
        "exits": [
          {
            "to": "S01",
            "travelMinutes": 10,
            "when": {
              "always": true
            },
            "blockedText": "无法返回摩勒住宅。"
          },
          {
            "to": "S02",
            "travelMinutes": 10,
            "when": {
              "factKnown": "F05"
            },
            "blockedText": "你们还没有质询蒙特利尔的依据。"
          },
          {
            "to": "S04",
            "travelMinutes": 10,
            "when": {
              "any": [
                {
                  "factKnown": "F06"
                },
                {
                  "factKnown": "F08"
                }
              ]
            },
            "blockedText": "酒保还没有透露贝尔街的方向。"
          }
        ]
      },
      {
        "id": "S04",
        "name": "卡森其药店",
        "chapterTitle": "第二幕：街区调查",
        "description": "贝尔街14号一间废弃多年的药店，门面破败，门锁仍在，内部没有营业迹象。",
        "aliases": [
          "药店",
          "废弃药店"
        ],
        "assetId": "scene.S04",
        "npcIds": [],
        "itemIds": [
          "I07",
          "I08"
        ],
        "dmFactIds": [
          "F03",
          "F11"
        ],
        "exits": [
          {
            "to": "S01",
            "travelMinutes": 20,
            "when": {
              "always": true
            },
            "blockedText": "无法返回摩勒住宅。"
          },
          {
            "to": "S02",
            "travelMinutes": 15,
            "when": {
              "always": true
            },
            "blockedText": "无法前往警局。"
          },
          {
            "to": "S03",
            "travelMinutes": 10,
            "when": {
              "always": true
            },
            "blockedText": "无法前往老赫特酒吧。"
          },
          {
            "to": "S05",
            "travelMinutes": 25,
            "when": {
              "factKnown": "F09"
            },
            "blockedText": "没有地图笔记就无法在浓雾中定位扶桑花号。"
          }
        ]
      },
      {
        "id": "S05",
        "name": "泰晤士港·扶桑花号",
        "chapterTitle": "终幕：扶桑花号",
        "description": "泰晤士港的偏僻泊位，浓雾覆盖水面，扶桑花号正准备离港。",
        "aliases": [
          "泰晤士港",
          "港口",
          "码头",
          "码头区",
          "扶桑花号"
        ],
        "assetId": "scene.S05",
        "npcIds": [
          "N05",
          "N02"
        ],
        "itemIds": [],
        "dmFactIds": [
          "F01",
          "F03",
          "F12",
          "F13"
        ],
        "exits": [
          {
            "to": "S04",
            "travelMinutes": 25,
            "when": {
              "not": {
                "encounter": "ENC01",
                "state": "active"
              }
            },
            "blockedText": "遭遇尚未解决，无法安全离开。"
          }
        ]
      }
    ],
    "npcs": [
      {
        "id": "N01",
        "name": "伊莎贝拉·摩勒",
        "role": "委托人",
        "attitude": "友好",
        "appearance": "二十余岁，面色苍白，衣着得体但明显缺乏休息。",
        "aliases": [
          "伊莎贝拉",
          "摩勒小姐"
        ],
        "hp": 8,
        "assetId": "npc.N01",
        "knowledgeFactIds": [
          "F04"
        ],
        "dmFactIds": [
          "F01"
        ]
      },
      {
        "id": "N02",
        "name": "埃里克·摩勒",
        "role": "失踪者",
        "attitude": "未知",
        "appearance": "五十二岁的商人，神情疲惫，留着修整整齐的胡须。",
        "aliases": [
          "埃里克",
          "摩勒先生"
        ],
        "hp": 10,
        "assetId": "npc.N02",
        "knowledgeFactIds": [],
        "dmFactIds": [
          "F01"
        ]
      },
      {
        "id": "N03",
        "name": "洛夫·蒙特利尔",
        "role": "警察局长",
        "attitude": "警惕",
        "appearance": "四十八岁，制服笔挺，目光冷淡而审慎。",
        "aliases": [
          "蒙特利尔",
          "蒙特利尔局长"
        ],
        "hp": 13,
        "assetId": "npc.N03",
        "knowledgeFactIds": [
          "F02"
        ],
        "dmFactIds": [
          "F02",
          "F11"
        ]
      },
      {
        "id": "N04",
        "name": "老赫特之家酒保",
        "role": "街区线人",
        "attitude": "中立",
        "appearance": "壮实的中年酒保，总在一边擦杯子一边观察客人。",
        "aliases": [
          "酒保",
          "老赫特酒保"
        ],
        "hp": 12,
        "assetId": "npc.N04",
        "knowledgeFactIds": [
          "F08"
        ],
        "dmFactIds": []
      },
      {
        "id": "N05",
        "name": "扶桑花号交涉代表",
        "role": "深潜者代表",
        "attitude": "警惕",
        "appearance": "灰绿色皮肤覆着湿润鳞片，蹼状双手始终靠近船舷，幽光眼睛警惕地观察来客。",
        "aliases": [
          "深潜者代表",
          "交涉代表",
          "深潜者",
          "混种"
        ],
        "hp": 11,
        "assetId": "npc.N05",
        "knowledgeFactIds": [],
        "dmFactIds": [
          "F13"
        ]
      }
    ],
    "encounters": [
      {
        "id": "ENC01",
        "name": "扶桑花号深潜者",
        "count": 4,
        "hpEach": 11,
        "skills": {
          "格斗": 45,
          "射击": 45,
          "闪避": 30,
          "聆听": 50,
          "游泳": 60
        },
        "attacks": [
          {
            "name": "爪击",
            "skill": 45,
            "damage": "1d3"
          },
          {
            "name": ".32手枪",
            "skill": 45,
            "damage": "1d8"
          }
        ],
        "resolutionMode": "narrator_assisted"
      },
      {
        "id": "ENC02",
        "name": "蒙特利尔雇佣的暴徒",
        "count": 3,
        "hpEach": 15,
        "skills": {
          "格斗": 60,
          "射击": 30,
          "闪避": 30
        },
        "attacks": [
          {
            "name": "拳脚",
            "skill": 60,
            "damage": "1d3+1"
          },
          {
            "name": "双管霰弹枪",
            "skill": 30,
            "damage": "2d6"
          }
        ],
        "resolutionMode": "narrator_assisted"
      }
    ],
    "items": [
      {
        "id": "I01",
        "name": "便签",
        "sceneId": "S01",
        "appearance": "书房桌面上写有“别来找我”的便签，墨迹尚未完全干透。",
        "aliases": [
          "求助便签"
        ],
        "factIds": [],
        "discovery": {
          "skill": "侦查",
          "difficulty": "普通",
          "failForward": "即使失败也能看到文字，但无法判断笔触异常，并推进5分钟。",
          "successEventId": "EV_FIND_I01",
          "failureEventId": "EV_FAIL_I01"
        },
        "fallbackEventId": "EV_RECOVER_I01"
      },
      {
        "id": "I02",
        "name": "合影照片",
        "sceneId": "S01",
        "appearance": "书桌抽屉里一张埃里克与蒙特利尔的旧合影。",
        "aliases": [
          "合影",
          "旧合影",
          "照片"
        ],
        "factIds": [
          "F05"
        ],
        "discovery": {
          "skill": "侦查",
          "difficulty": "普通",
          "failForward": "失败仍能发现照片，但会惊动伊莎贝拉并推进10分钟。",
          "successEventId": "EV_FIND_I02",
          "failureEventId": "EV_FAIL_I02"
        },
        "fallbackEventId": "EV_RECOVER_I02"
      },
      {
        "id": "I03",
        "name": "名片",
        "sceneId": "S01",
        "appearance": "一张印有埃里克旧公司信息的泛黄名片。",
        "aliases": [
          "旧名片"
        ],
        "factIds": [],
        "discovery": {
          "skill": "侦查",
          "difficulty": "自动",
          "failForward": "公开摆放，无需检定。",
          "successEventId": "EV_FIND_I03",
          "failureEventId": "EV_FIND_I03"
        },
        "fallbackEventId": "EV_RECOVER_I03"
      },
      {
        "id": "I04",
        "name": "小册子",
        "sceneId": "S01",
        "appearance": "夹在书架缝隙里的普通小册子，夹页似乎受过特殊处理。",
        "aliases": [
          "册子"
        ],
        "factIds": [
          "F06"
        ],
        "discovery": {
          "skill": "侦查",
          "difficulty": "普通",
          "failForward": "失败仍发现受潮夹页，艾达可通过加热或医学知识恢复隐写内容，但推进15分钟。",
          "successEventId": "EV_DISCOVER_I04",
          "failureEventId": "EV_FAIL_I04"
        },
        "fallbackEventId": "EV_RECOVER_I04"
      },
      {
        "id": "I05",
        "name": "白色粉末样品",
        "sceneId": "S01",
        "appearance": "车库暗格中的小袋白色粉末，颗粒细腻，气味淡苦。",
        "aliases": [
          "鸦片样品",
          "白色粉末",
          "粉末样品"
        ],
        "factIds": [
          "F07"
        ],
        "discovery": {
          "skill": "医学",
          "difficulty": "普通",
          "failForward": "失败只能确认其可疑并推进10分钟，之后可由药店记录或蒙特利尔反应补证。",
          "successEventId": "EV_FIND_I05",
          "failureEventId": "EV_FAIL_I05"
        },
        "fallbackEventId": "EV_RECOVER_I05"
      },
      {
        "id": "I06",
        "name": "报纸残片",
        "sceneId": "S01",
        "appearance": "垃圾桶中的报纸残片，保留着扫毒英雄通稿和人物照片的一部分。",
        "aliases": [
          "报纸碎片"
        ],
        "factIds": [
          "F02"
        ],
        "discovery": {
          "skill": "侦查",
          "difficulty": "普通",
          "failForward": "失败仍能带走残片，之后可与合影比对。",
          "successEventId": "EV_FIND_I06",
          "failureEventId": "EV_FAIL_I06"
        },
        "fallbackEventId": "EV_RECOVER_I06"
      },
      {
        "id": "I07",
        "name": "深潜者地图笔记",
        "sceneId": "S04",
        "appearance": "后厅油布包中的潮湿手绘地图，标注了港口偏僻泊位。",
        "aliases": [
          "潮湿的地图笔记",
          "地图笔记",
          "手绘地图"
        ],
        "factIds": [
          "F09"
        ],
        "discovery": {
          "skill": "侦查",
          "difficulty": "普通",
          "failForward": "失败仍能从残片辨认扶桑花号泊位，但暴徒或深潜者警觉度增加。",
          "successEventId": "EV_S04_MAP",
          "failureEventId": "EV_FAIL_I07"
        },
        "fallbackEventId": "EV_RECOVER_I07"
      },
      {
        "id": "I08",
        "name": "雪茄头",
        "sceneId": "S04",
        "appearance": "柜台附近未燃尽的雪茄头，品牌标记仍然清晰。",
        "aliases": [
          "雪茄烟头"
        ],
        "factIds": [
          "F10"
        ],
        "discovery": {
          "skill": "侦查",
          "difficulty": "普通",
          "failForward": "失败仍可收集，回看埃里克物品后自动完成比对。",
          "successEventId": "EV_S04_CIGAR",
          "failureEventId": "EV_FAIL_I08"
        },
        "fallbackEventId": "EV_RECOVER_I08"
      }
    ]
  },
  "progression": {
    "variables": [
      {
        "id": "commissionAccepted",
        "type": "boolean",
        "default": false
      },
      {
        "id": "oldHethLead",
        "type": "boolean",
        "default": false
      },
      {
        "id": "metMontreal",
        "type": "boolean",
        "default": false
      },
      {
        "id": "hybridEscaped",
        "type": "boolean",
        "default": false
      },
      {
        "id": "thugAlert",
        "type": "boolean",
        "default": false
      },
      {
        "id": "finaleRoute",
        "type": "string",
        "default": "undecided"
      },
      {
        "id": "combatRoundStarted",
        "type": "boolean",
        "default": false
      },
      {
        "id": "ericRescued",
        "type": "boolean",
        "default": false
      }
    ],
    "acts": [
      {
        "id": "A01",
        "title": "第一幕：接受委托",
        "order": 1
      },
      {
        "id": "A02",
        "title": "第二幕：街区调查",
        "order": 2
      },
      {
        "id": "A03",
        "title": "终幕：扶桑花号",
        "order": 3
      }
    ],
    "objectives": [
      {
        "id": "O01",
        "beatId": "B01",
        "title": "接受委托",
        "playerText": "与伊莎贝拉确认委托和埃里克失踪的基本情况。",
        "required": true
      },
      {
        "id": "O02",
        "beatId": "B02",
        "title": "找到下一处调查方向",
        "playerText": "在摩勒住宅寻找能指向警局、酒吧或贝尔街的证据。",
        "required": true
      },
      {
        "id": "O03",
        "beatId": "B03",
        "title": "质询蒙特利尔",
        "playerText": "调查蒙特利尔与埃里克的关系并观察他的反应。",
        "required": false
      },
      {
        "id": "O04",
        "beatId": "B04",
        "title": "获取“老鼠”情报",
        "playerText": "说服老赫特酒保透露贝尔街相关消息。",
        "required": false
      },
      {
        "id": "O05",
        "beatId": "B05",
        "title": "调查卡森其药店",
        "playerText": "应对浓雾与追兵，找到扶桑花号的位置。",
        "required": true
      },
      {
        "id": "O06",
        "beatId": "B06",
        "title": "决定终幕路线",
        "playerText": "在扶桑花号上选择阻止深潜者或尝试交涉。",
        "required": true
      },
      {
        "id": "O07",
        "beatId": "B06",
        "title": "阻止扶桑花号离港",
        "playerText": "在七轮内结束冲突并救出埃里克。",
        "required": false
      },
      {
        "id": "O08",
        "beatId": "B06",
        "title": "完成交涉",
        "playerText": "先听懂对方诉求，再说服其释放埃里克。",
        "required": false
      }
    ],
    "beats": [
      {
        "id": "B01",
        "actId": "A01",
        "title": "伊莎贝拉的委托",
        "kind": "mandatory",
        "sceneIds": [
          "S01"
        ],
        "activation": {
          "always": true
        },
        "completion": {
          "variable": "commissionAccepted",
          "op": "eq",
          "value": true
        },
        "objectiveIds": [
          "O01"
        ],
        "dmFactIds": [
          "F01",
          "F04"
        ],
        "allowedEventIds": [
          "EV_ACCEPT_COMMISSION",
          "EV_OPENING_RECOVERY"
        ],
        "softEscalationAfter": 3,
        "hardRecoveryAfter": 6,
        "softPrompt": "伊莎贝拉主动说明父亲失踪日期、警方无进展和父亲常去老赫特酒吧。",
        "recoveryEventId": "EV_OPENING_RECOVERY",
        "nextBeatIds": [
          "B02"
        ]
      },
      {
        "id": "B02",
        "actId": "A01",
        "title": "摩勒住宅调查",
        "kind": "mandatory",
        "sceneIds": [
          "S01"
        ],
        "activation": {
          "beat": "B01",
          "status": "completed"
        },
        "completion": {
          "any": [
            {
              "factKnown": "F05"
            },
            {
              "factKnown": "F06"
            },
            {
              "factKnown": "F08"
            }
          ]
        },
        "objectiveIds": [
          "O02"
        ],
        "dmFactIds": [
          "F01",
          "F02"
        ],
        "allowedEventIds": [
          "EV_FIND_I01",
          "EV_FAIL_I01",
          "EV_FIND_I02",
          "EV_FAIL_I02",
          "EV_FIND_I03",
          "EV_DISCOVER_I04",
          "EV_FAIL_I04",
          "EV_FIND_I04",
          "EV_FIND_I05",
          "EV_FAIL_I05",
          "EV_FIND_I06",
          "EV_FAIL_I06",
          "EV_HOUSE_RECOVERY",
          "EV_RECOVER_I01",
          "EV_RECOVER_I02",
          "EV_RECOVER_I03",
          "EV_RECOVER_I04",
          "EV_RECOVER_I05",
          "EV_RECOVER_I06"
        ],
        "softEscalationAfter": 3,
        "hardRecoveryAfter": 6,
        "softPrompt": "从书桌抽屉、书架夹缝、垃圾桶或车库暗格中选择一处给出明确可调查迹象。",
        "recoveryEventId": "EV_HOUSE_RECOVERY",
        "nextBeatIds": [
          "B03",
          "B04",
          "B05"
        ]
      },
      {
        "id": "B03",
        "actId": "A02",
        "title": "警局支线",
        "kind": "optional",
        "sceneIds": [
          "S02"
        ],
        "activation": {
          "factKnown": "F05"
        },
        "completion": {
          "variable": "metMontreal",
          "op": "eq",
          "value": true
        },
        "objectiveIds": [
          "O03"
        ],
        "dmFactIds": [
          "F02",
          "F11"
        ],
        "allowedEventIds": [
          "EV_MEET_MONTREAL"
        ],
        "softEscalationAfter": 0,
        "hardRecoveryAfter": 0,
        "softPrompt": "蒙特利尔保持强硬和回避，不主动承认犯罪事实。",
        "recoveryEventId": "",
        "nextBeatIds": [
          "B04",
          "B05"
        ]
      },
      {
        "id": "B04",
        "actId": "A02",
        "title": "老赫特酒吧支线",
        "kind": "optional",
        "sceneIds": [
          "S03"
        ],
        "activation": {
          "variable": "oldHethLead",
          "op": "eq",
          "value": true
        },
        "completion": {
          "factKnown": "F08"
        },
        "objectiveIds": [
          "O04"
        ],
        "dmFactIds": [
          "F08"
        ],
        "allowedEventIds": [
          "EV_BARTENDER_RAT"
        ],
        "softEscalationAfter": 0,
        "hardRecoveryAfter": 0,
        "softPrompt": "酒保只在获得酒水、金钱或可信理由后提供“老鼠”线索。",
        "recoveryEventId": "",
        "nextBeatIds": [
          "B05"
        ]
      },
      {
        "id": "B05",
        "actId": "A02",
        "title": "卡森其药店",
        "kind": "mandatory",
        "sceneIds": [
          "S04"
        ],
        "activation": {
          "any": [
            {
              "factKnown": "F06"
            },
            {
              "factKnown": "F08"
            }
          ]
        },
        "completion": {
          "factKnown": "F09"
        },
        "objectiveIds": [
          "O05"
        ],
        "dmFactIds": [
          "F03",
          "F09",
          "F10",
          "F11"
        ],
        "allowedEventIds": [
          "EV_S04_FOG",
          "EV_S04_MAP",
          "EV_FAIL_I07",
          "EV_S04_CIGAR",
          "EV_FAIL_I08",
          "EV_S04_THUGS",
          "EV_PHARMACY_RECOVERY",
          "EV_RECOVER_I07",
          "EV_RECOVER_I08"
        ],
        "softEscalationAfter": 3,
        "hardRecoveryAfter": 6,
        "softPrompt": "浓雾加重，后厅油布包和柜台附近的痕迹变得更显眼。",
        "recoveryEventId": "EV_PHARMACY_RECOVERY",
        "nextBeatIds": [
          "B06"
        ]
      },
      {
        "id": "B06",
        "actId": "A03",
        "title": "扶桑花号终幕",
        "kind": "finale",
        "sceneIds": [
          "S05"
        ],
        "activation": {
          "factKnown": "F09"
        },
        "completion": {
          "any": [
            {
              "encounter": "ENC01",
              "state": "won"
            },
            {
              "eventFired": "EV_NEGOTIATION_SUCCESS"
            },
            {
              "clock": "fusangEscape",
              "op": "gte",
              "value": 7
            }
          ]
        },
        "objectiveIds": [
          "O06",
          "O07",
          "O08"
        ],
        "dmFactIds": [
          "F01",
          "F03",
          "F12",
          "F13"
        ],
        "allowedEventIds": [
          "EV_CHOOSE_COMBAT",
          "EV_CHOOSE_NEGOTIATION",
          "EV_COMBAT_ATTACK",
          "EV_COMBAT_HIT",
          "EV_COMBAT_ROUND",
          "EV_COMBAT_WIN",
          "EV_NEGOTIATION_LISTEN",
          "EV_NEGOTIATION_UNDERSTOOD",
          "EV_NEGOTIATION_LISTEN_FAILED",
          "EV_NEGOTIATION_SUCCESS",
          "EV_NEGOTIATION_FAILED",
          "EV_RESCUE_ERIC"
        ],
        "softEscalationAfter": 3,
        "hardRecoveryAfter": 6,
        "softPrompt": "船笛和收缆声提醒调查员，扶桑花号即将离港，必须立刻选择行动路线。",
        "recoveryEventId": "EV_CHOOSE_COMBAT",
        "nextBeatIds": []
      }
    ],
    "storyEvents": [
      {
        "id": "EV_ACCEPT_COMMISSION",
        "beatId": "B01",
        "title": "接受委托",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "setVariable": "commissionAccepted",
            "value": true
          },
          {
            "setVariable": "oldHethLead",
            "value": true
          },
          {
            "revealFact": "F04"
          },
          {
            "completeObjective": "O01"
          },
          {
            "completeBeat": "B01"
          },
          {
            "activateBeat": "B02"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "伊莎贝拉确认委托，并提供父亲失踪日期、警方无进展以及老赫特酒吧这一生活线索。"
      },
      {
        "id": "EV_OPENING_RECOVERY",
        "beatId": "B01",
        "title": "委托回收",
        "trigger": "automatic",
        "when": {
          "variable": "commissionAccepted",
          "op": "eq",
          "value": false
        },
        "effects": [
          {
            "setVariable": "commissionAccepted",
            "value": true
          },
          {
            "setVariable": "oldHethLead",
            "value": true
          },
          {
            "revealFact": "F04"
          },
          {
            "completeObjective": "O01"
          },
          {
            "completeBeat": "B01"
          },
          {
            "activateBeat": "B02"
          },
          {
            "advanceTime": 10
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "伊莎贝拉提高酬金并把父亲常去老赫特酒吧的情况写入委托资料，调查正式开始。"
      },
      {
        "id": "EV_FIND_I01",
        "beatId": "B02",
        "title": "发现便签",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I01"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员发现写有“别来找我”的便签。"
      },
      {
        "id": "EV_FAIL_I01",
        "beatId": "B02",
        "title": "失败推进·便签",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I01"
          },
          {
            "advanceTime": 5
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "虽然没能判断笔触异常，调查员仍看清便签上的“别来找我”，但耽误了五分钟。"
      },
      {
        "id": "EV_FIND_I02",
        "beatId": "B02",
        "title": "发现合影",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I02"
          },
          {
            "revealFact": "F05"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "合影把埃里克与蒙特利尔联系起来，警局成为合法调查方向。"
      },
      {
        "id": "EV_FAIL_I02",
        "beatId": "B02",
        "title": "失败推进·合影",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I02"
          },
          {
            "revealFact": "F05"
          },
          {
            "advanceTime": 10
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "翻找声惊动了伊莎贝拉，但她仍认出合影中的蒙特利尔；调查因此耽误十分钟。"
      },
      {
        "id": "EV_FIND_I03",
        "beatId": "B02",
        "title": "发现名片",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I03"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员收起埃里克旧公司的名片。"
      },
      {
        "id": "EV_DISCOVER_I04",
        "beatId": "B02",
        "title": "发现小册子",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I04"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员在书架夹缝中发现夹页受过特殊处理的小册子，但尚未读出隐藏内容。"
      },
      {
        "id": "EV_FAIL_I04",
        "beatId": "B02",
        "title": "失败推进·小册子",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I04"
          },
          {
            "advanceTime": 15
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员仍找到受潮的小册子，却没能读出隐藏内容；反复翻找耽误十五分钟。"
      },
      {
        "id": "EV_FIND_I04",
        "beatId": "B02",
        "title": "破译小册子",
        "trigger": "manual",
        "when": {
          "all": [
            {
              "sceneIs": "S01"
            },
            {
              "clue": "I04",
              "status": "discovered"
            }
          ]
        },
        "effects": [
          {
            "analyzeClue": "I04"
          },
          {
            "revealFact": "F06"
          },
          {
            "setVariable": "oldHethLead",
            "value": true
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "加热显出隐写文字“贝尔街14号卡森其药店”，同时强化了老赫特这一街区线索。"
      },
      {
        "id": "EV_FIND_I05",
        "beatId": "B02",
        "title": "发现粉末样品",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I05"
          },
          {
            "analyzeClue": "I05"
          },
          {
            "revealFact": "F07"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "医学分析确认暗格中的白色粉末是高纯度鸦片。"
      },
      {
        "id": "EV_FAIL_I05",
        "beatId": "B02",
        "title": "失败推进·粉末",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I05"
          },
          {
            "advanceTime": 10
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "艾达只能确认白色粉末样品十分可疑，无法立即定性；检查耽误十分钟。"
      },
      {
        "id": "EV_FIND_I06",
        "beatId": "B02",
        "title": "发现报纸残片",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I06"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "报纸残片保留着蒙特利尔的扫毒英雄通稿，可与合影交叉比对。"
      },
      {
        "id": "EV_FAIL_I06",
        "beatId": "B02",
        "title": "失败推进·报纸",
        "trigger": "manual",
        "when": {
          "sceneIs": "S01"
        },
        "effects": [
          {
            "discoverClue": "I06"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员仍带走了破损严重的报纸残片，人物照片需要之后与合影比对。"
      },
      {
        "id": "EV_HOUSE_RECOVERY",
        "beatId": "B02",
        "title": "住宅主线回收",
        "trigger": "automatic",
        "when": {
          "not": {
            "factKnown": "F06"
          }
        },
        "effects": [
          {
            "discoverClue": "I04"
          },
          {
            "analyzeClue": "I04"
          },
          {
            "revealFact": "F06"
          },
          {
            "setVariable": "oldHethLead",
            "value": true
          },
          {
            "advanceTime": 15
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "伊莎贝拉整理父亲遗物时发现小册子受热显字，代价是调查耗去了额外时间。"
      },
      {
        "id": "EV_RECOVER_I01",
        "beatId": "B02",
        "title": "恢复便签",
        "trigger": "automatic",
        "when": {
          "clue": "I01",
          "status": "destroyed"
        },
        "effects": [
          {
            "discoverClue": "I01"
          },
          {
            "advanceTime": 5
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员从残留纸片中恢复了便签正文。"
      },
      {
        "id": "EV_RECOVER_I02",
        "beatId": "B02",
        "title": "恢复合影",
        "trigger": "automatic",
        "when": {
          "clue": "I02",
          "status": "destroyed"
        },
        "effects": [
          {
            "revealFact": "F05"
          },
          {
            "advanceTime": 10
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "伊莎贝拉确认照片上的另一人是蒙特利尔。"
      },
      {
        "id": "EV_RECOVER_I03",
        "beatId": "B02",
        "title": "恢复名片",
        "trigger": "automatic",
        "when": {
          "clue": "I03",
          "status": "destroyed"
        },
        "effects": [
          {
            "discoverClue": "I03"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "伊莎贝拉从通讯录中抄出名片上的旧公司信息。"
      },
      {
        "id": "EV_RECOVER_I04",
        "beatId": "B02",
        "title": "恢复小册子线索",
        "trigger": "automatic",
        "when": {
          "clue": "I04",
          "status": "destroyed"
        },
        "effects": [
          {
            "revealFact": "F06"
          },
          {
            "setVariable": "oldHethLead",
            "value": true
          },
          {
            "advanceTime": 15
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "烧剩的夹页仍留下“贝尔14”字样，足以继续调查。"
      },
      {
        "id": "EV_RECOVER_I05",
        "beatId": "B02",
        "title": "恢复粉末证据",
        "trigger": "automatic",
        "when": {
          "clue": "I05",
          "status": "destroyed"
        },
        "effects": [
          {
            "revealFact": "F07"
          },
          {
            "advanceTime": 10
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "暗格残留物仍能证明这里存放过鸦片。"
      },
      {
        "id": "EV_RECOVER_I06",
        "beatId": "B02",
        "title": "恢复报纸信息",
        "trigger": "automatic",
        "when": {
          "clue": "I06",
          "status": "destroyed"
        },
        "effects": [
          {
            "setVariable": "metMontreal",
            "value": true
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "伊莎贝拉认出残片上的人物是蒙特利尔。"
      },
      {
        "id": "EV_MEET_MONTREAL",
        "beatId": "B03",
        "title": "蒙特利尔阻挠调查",
        "trigger": "manual",
        "when": {
          "sceneIs": "S02"
        },
        "effects": [
          {
            "setVariable": "metMontreal",
            "value": true
          },
          {
            "setVariable": "thugAlert",
            "value": true
          },
          {
            "completeObjective": "O03"
          },
          {
            "completeBeat": "B03"
          },
          {
            "advanceTime": 15
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "蒙特利尔回避关键问题，并冷淡地结束了会面。"
      },
      {
        "id": "EV_BARTENDER_RAT",
        "beatId": "B04",
        "title": "酒保提供“老鼠”线索",
        "trigger": "manual",
        "when": {
          "sceneIs": "S03"
        },
        "effects": [
          {
            "revealFact": "F08"
          },
          {
            "completeObjective": "O04"
          },
          {
            "completeBeat": "B04"
          },
          {
            "activateBeat": "B05"
          },
          {
            "advanceTime": 10
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "酒保在得到酒水、金钱或可信理由后，指出贝尔街14号的废弃药店。"
      },
      {
        "id": "EV_S04_FOG",
        "beatId": "B05",
        "title": "深潜者撤离与浓雾",
        "trigger": "sceneEnter",
        "when": {
          "sceneIs": "S04"
        },
        "effects": [
          {
            "setVariable": "hybridEscaped",
            "value": true
          },
          {
            "applyDelta": "san",
            "target": "party",
            "value": -1
          },
          {
            "advanceTime": 10
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "非人的身影从后门撤离，咒术浓雾涌入药店；所有在场调查员承受最低1点SAN损失。"
      },
      {
        "id": "EV_S04_MAP",
        "beatId": "B05",
        "title": "获得地图笔记",
        "trigger": "manual",
        "when": {
          "sceneIs": "S04"
        },
        "effects": [
          {
            "discoverClue": "I07"
          },
          {
            "analyzeClue": "I07"
          },
          {
            "revealFact": "F09"
          },
          {
            "completeObjective": "O05"
          },
          {
            "completeBeat": "B05"
          },
          {
            "activateBeat": "B06"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "后厅油布包中的地图笔记标出了泰晤士港扶桑花号的位置。"
      },
      {
        "id": "EV_FAIL_I07",
        "beatId": "B05",
        "title": "失败推进·地图",
        "trigger": "manual",
        "when": {
          "sceneIs": "S04"
        },
        "effects": [
          {
            "discoverClue": "I07"
          },
          {
            "analyzeClue": "I07"
          },
          {
            "revealFact": "F09"
          },
          {
            "completeObjective": "O05"
          },
          {
            "completeBeat": "B05"
          },
          {
            "activateBeat": "B06"
          },
          {
            "setVariable": "thugAlert",
            "value": true
          },
          {
            "advanceTime": 10
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "地图笔记虽被水浸坏，残片仍能定位泰晤士港扶桑花号；敌人警觉且调查耽误十分钟。"
      },
      {
        "id": "EV_S04_CIGAR",
        "beatId": "B05",
        "title": "发现雪茄头",
        "trigger": "manual",
        "when": {
          "sceneIs": "S04"
        },
        "effects": [
          {
            "discoverClue": "I08"
          },
          {
            "analyzeClue": "I08"
          },
          {
            "revealFact": "F10"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "雪茄头与埃里克常用品牌一致，证明他近期来过药店。"
      },
      {
        "id": "EV_FAIL_I08",
        "beatId": "B05",
        "title": "失败推进·雪茄",
        "trigger": "manual",
        "when": {
          "sceneIs": "S04"
        },
        "effects": [
          {
            "discoverClue": "I08"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员仍收起雪茄头，但暂时无法辨认品牌，需与埃里克的物品比对。"
      },
      {
        "id": "EV_S04_THUGS",
        "beatId": "B05",
        "title": "暴徒抵达贝尔街",
        "trigger": "sceneEnter",
        "when": {
          "all": [
            {
              "variable": "metMontreal",
              "op": "eq",
              "value": true
            },
            {
              "worldTime": true,
              "op": "gte",
              "value": "1920-07-13T19:00"
            }
          ]
        },
        "effects": [
          {
            "resolveEncounter": "ENC02",
            "state": "resolved"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "三名身份不明的暴徒追到贝尔街，短暂封住药店外的退路后消失在浓雾中。"
      },
      {
        "id": "EV_PHARMACY_RECOVERY",
        "beatId": "B05",
        "title": "药店主线回收",
        "trigger": "automatic",
        "when": {
          "not": {
            "factKnown": "F09"
          }
        },
        "effects": [
          {
            "discoverClue": "I07"
          },
          {
            "analyzeClue": "I07"
          },
          {
            "revealFact": "F09"
          },
          {
            "completeObjective": "O05"
          },
          {
            "completeBeat": "B05"
          },
          {
            "activateBeat": "B06"
          },
          {
            "advanceTime": 15
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "即使地图受损，水渍和船名残片仍足以定位扶桑花号，但敌人获得了额外准备时间。"
      },
      {
        "id": "EV_RECOVER_I07",
        "beatId": "B05",
        "title": "恢复港口位置",
        "trigger": "automatic",
        "when": {
          "clue": "I07",
          "status": "destroyed"
        },
        "effects": [
          {
            "revealFact": "F09"
          },
          {
            "advanceTime": 15
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "地图残片与港口灯号相互印证，恢复了扶桑花号泊位。"
      },
      {
        "id": "EV_RECOVER_I08",
        "beatId": "B05",
        "title": "恢复雪茄证据",
        "trigger": "automatic",
        "when": {
          "clue": "I08",
          "status": "destroyed"
        },
        "effects": [
          {
            "revealFact": "F10"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "柜台残留的烟灰品牌仍能与埃里克的雪茄盒对应。"
      },
      {
        "id": "EV_CHOOSE_COMBAT",
        "beatId": "B06",
        "title": "选择战斗路线",
        "trigger": "manual",
        "when": {
          "all": [
            {
              "sceneIs": "S05"
            },
            {
              "variable": "finaleRoute",
              "op": "eq",
              "value": "undecided"
            }
          ]
        },
        "effects": [
          {
            "setVariable": "finaleRoute",
            "value": "combat"
          },
          {
            "completeObjective": "O06"
          },
          {
            "activateObjective": "O07"
          },
          {
            "startEncounter": "ENC01",
            "route": "combat"
          },
          {
            "startClock": "fusangEscape",
            "value": 0,
            "visible": true
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员以武力阻止深潜者，扶桑花号逃脱时钟开始计数。"
      },
      {
        "id": "EV_CHOOSE_NEGOTIATION",
        "beatId": "B06",
        "title": "选择交涉路线",
        "trigger": "manual",
        "when": {
          "all": [
            {
              "sceneIs": "S05"
            },
            {
              "variable": "finaleRoute",
              "op": "eq",
              "value": "undecided"
            }
          ]
        },
        "effects": [
          {
            "setVariable": "finaleRoute",
            "value": "negotiation"
          },
          {
            "completeObjective": "O06"
          },
          {
            "activateObjective": "O08"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "调查员暂缓攻击，与扶桑花号交涉代表保持距离，尝试听懂深潜者的诉求。"
      },
      {
        "id": "EV_COMBAT_ROUND",
        "beatId": "B06",
        "title": "战斗轮推进",
        "trigger": "turnEnd",
        "when": {
          "all": [
            {
              "variable": "finaleRoute",
              "op": "eq",
              "value": "combat"
            },
            {
              "variable": "combatRoundStarted",
              "op": "eq",
              "value": true
            },
            {
              "encounter": "ENC01",
              "state": "active"
            }
          ]
        },
        "effects": [
          {
            "updateEncounter": "ENC01",
            "field": "round",
            "amount": 1
          },
          {
            "tickClock": "fusangEscape",
            "amount": 1
          }
        ],
        "once": false,
        "playerVisible": true,
        "narrativeCue": "船员继续收缆，扶桑花号距离逃脱又近一轮。"
      },
      {
        "id": "EV_COMBAT_ATTACK",
        "beatId": "B06",
        "title": "攻击深潜者",
        "trigger": "manual",
        "when": {
          "all": [
            {
              "variable": "finaleRoute",
              "op": "eq",
              "value": "combat"
            },
            {
              "encounter": "ENC01",
              "state": "active"
            },
            {
              "clock": "fusangEscape",
              "op": "lt",
              "value": 7
            }
          ]
        },
        "effects": [
          {
            "setVariable": "combatRoundStarted",
            "value": true
          },
          {
            "requestCheck": "CHECK_COMBAT",
            "skill": "格斗（拳）",
            "difficulty": "普通",
            "reason": "在甲板混战中使一名深潜者失去战斗能力"
          }
        ],
        "once": false,
        "playerVisible": true,
        "narrativeCue": "调查员抓住机会攻击一名仍在抵抗的深潜者。"
      },
      {
        "id": "EV_COMBAT_HIT",
        "beatId": "B06",
        "title": "有效命中深潜者",
        "trigger": "checkResolved",
        "when": {
          "all": [
            {
              "check": "CHECK_COMBAT",
              "outcome": "success"
            },
            {
              "encounter": "ENC01",
              "state": "active"
            }
          ]
        },
        "effects": [
          {
            "updateEncounter": "ENC01",
            "field": "opponentHp",
            "amount": -11
          },
          {
            "updateEncounter": "ENC01",
            "field": "defeated",
            "amount": 1
          }
        ],
        "once": false,
        "playerVisible": true,
        "narrativeCue": "攻击奏效，一名深潜者失去战斗能力。"
      },
      {
        "id": "EV_COMBAT_WIN",
        "beatId": "B06",
        "title": "击败深潜者",
        "trigger": "automatic",
        "when": {
          "all": [
            {
              "variable": "finaleRoute",
              "op": "eq",
              "value": "combat"
            },
            {
              "encounter": "ENC01",
              "field": "opponentHp",
              "op": "lte",
              "value": 0
            },
            {
              "clock": "fusangEscape",
              "op": "lt",
              "value": 7
            }
          ]
        },
        "effects": [
          {
            "resolveEncounter": "ENC01",
            "state": "won"
          },
          {
            "completeObjective": "O07"
          },
          {
            "setVariable": "ericRescued",
            "value": true
          },
          {
            "stopClock": "fusangEscape"
          },
          {
            "setEnding": "END_A"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "四名深潜者失去战斗能力，调查员及时救出埃里克。"
      },
      {
        "id": "EV_NEGOTIATION_LISTEN",
        "beatId": "B06",
        "title": "听懂深潜者诉求",
        "trigger": "manual",
        "when": {
          "variable": "finaleRoute",
          "op": "eq",
          "value": "negotiation"
        },
        "effects": [
          {
            "requestCheck": "CHECK_LISTEN",
            "skill": "聆听",
            "difficulty": "普通",
            "reason": "从非人声调中辨认其真正诉求"
          }
        ],
        "once": false,
        "playerVisible": true,
        "narrativeCue": "调查员需要先通过聆听检定理解对方的真正诉求。"
      },
      {
        "id": "EV_NEGOTIATION_UNDERSTOOD",
        "beatId": "B06",
        "title": "理解深潜者诉求",
        "trigger": "checkResolved",
        "when": {
          "check": "CHECK_LISTEN",
          "outcome": "success"
        },
        "effects": [
          {
            "revealFact": "F13"
          },
          {
            "requestCheck": "CHECK_PERSUADE",
            "skill": "说服",
            "difficulty": "困难",
            "reason": "说服深潜者释放埃里克并和平离开"
          }
        ],
        "once": false,
        "playerVisible": true,
        "narrativeCue": "调查员听懂了深潜者的底线：他们只要求带走走私货物并安全离港；若调查员承诺不追击，他们愿意释放埃里克。现在必须完成说服。"
      },
      {
        "id": "EV_NEGOTIATION_LISTEN_FAILED",
        "beatId": "B06",
        "title": "失败推进·交涉聆听",
        "trigger": "checkResolved",
        "when": {
          "any": [
            {
              "check": "CHECK_LISTEN",
              "outcome": "fail"
            },
            {
              "check": "CHECK_LISTEN",
              "outcome": "fumble"
            }
          ]
        },
        "effects": [
          {
            "revealFact": "F13"
          },
          {
            "advanceTime": 5
          },
          {
            "requestCheck": "CHECK_PERSUADE",
            "skill": "说服",
            "difficulty": "极难",
            "reason": "未能听清声调，只能依据反复手势在对方失去耐心前完成交涉"
          }
        ],
        "once": false,
        "playerVisible": true,
        "narrativeCue": "调查员没能听清非人声调，但反复手势仍表明深潜者只要求带走走私货物并安全离港；迟疑消磨了对方耐心，仍可尝试说服其释放埃里克，但难度提高为极难。"
      },
      {
        "id": "EV_NEGOTIATION_SUCCESS",
        "beatId": "B06",
        "title": "交涉成功",
        "trigger": "checkResolved",
        "when": {
          "check": "CHECK_PERSUADE",
          "outcome": "success"
        },
        "effects": [
          {
            "completeObjective": "O08"
          },
          {
            "setVariable": "ericRescued",
            "value": true
          },
          {
            "setEnding": "END_C"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "说服奏效，深潜者释放埃里克并同意和平离港。"
      },
      {
        "id": "EV_NEGOTIATION_FAILED",
        "beatId": "B06",
        "title": "交涉破裂",
        "trigger": "checkResolved",
        "when": {
          "any": [
            {
              "check": "CHECK_PERSUADE",
              "outcome": "fail"
            },
            {
              "check": "CHECK_PERSUADE",
              "outcome": "fumble"
            }
          ]
        },
        "effects": [
          {
            "failObjective": "O08"
          },
          {
            "setEnding": "END_B"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "最后的说服没有奏效，深潜者终止交涉，扶桑花号带着埃里克驶入浓雾。"
      },
      {
        "id": "EV_RESCUE_ERIC",
        "beatId": "B06",
        "title": "救出埃里克",
        "trigger": "automatic",
        "when": {
          "variable": "ericRescued",
          "op": "eq",
          "value": true
        },
        "effects": [
          {
            "revealFact": "F01"
          }
        ],
        "once": true,
        "playerVisible": true,
        "narrativeCue": "埃里克获救，但其走私身份也随证据暴露。"
      }
    ],
    "endings": [
      {
        "id": "END_A",
        "title": "结局A：击败深潜者",
        "summary": "深潜者被击败，埃里克获救，调查员阻止了扶桑花号逃脱。",
        "when": {
          "all": [
            {
              "encounter": "ENC01",
              "state": "won"
            },
            {
              "variable": "ericRescued",
              "op": "eq",
              "value": true
            }
          ]
        },
        "effects": [
          {
            "applyDelta": "san",
            "target": "party",
            "value": "1d3"
          },
          {
            "applyDelta": "money",
            "target": "party",
            "value": 200
          },
          {
            "applyDelta": "mythos",
            "target": "party",
            "value": "1d6"
          }
        ],
        "priority": 30
      },
      {
        "id": "END_B",
        "title": "结局B：深潜者逃脱",
        "summary": "调查员未能及时救出埃里克，扶桑花号载着深潜者和埃里克消失在泰晤士河浓雾中。",
        "when": {
          "all": [
            {
              "variable": "finaleRoute",
              "op": "eq",
              "value": "combat"
            },
            {
              "clock": "fusangEscape",
              "op": "gte",
              "value": 7
            }
          ]
        },
        "effects": [
          {
            "resolveEncounter": "ENC01",
            "state": "lost"
          },
          {
            "stopClock": "fusangEscape"
          },
          {
            "setEnding": "END_B"
          }
        ],
        "priority": 10
      },
      {
        "id": "END_C",
        "title": "结局C：和平交涉",
        "summary": "调查员听懂并说服深潜者释放埃里克，扶桑花号随后和平离港。",
        "when": {
          "eventFired": "EV_NEGOTIATION_SUCCESS"
        },
        "effects": [
          {
            "applyDelta": "san",
            "target": "party",
            "value": "1d6"
          },
          {
            "applyDelta": "money",
            "target": "party",
            "value": 100
          },
          {
            "applyDelta": "mythos",
            "target": "party",
            "value": "1d6"
          }
        ],
        "priority": 20
      }
    ]
  },
  "rules": {
    "entries": [
      {
        "id": "RULE_MONTREAL_LANGUAGE",
        "trigger": "checkRequested",
        "support": "enforced",
        "description": "对蒙特利尔使用语言类技能默认失败；心理学提高为困难难度。",
        "when": {
          "all": [
            {
              "sceneIs": "S02"
            },
            {
              "variable": "metMontreal",
              "op": "eq",
              "value": true
            }
          ]
        },
        "effects": []
      },
      {
        "id": "RULE_TURN_TIME",
        "trigger": "afterAction",
        "support": "enforced",
        "description": "每个完成的正式DM回合推进五分钟世界时间。",
        "when": {
          "always": true
        },
        "effects": [
          {
            "advanceTime": 5
          }
        ]
      },
      {
        "id": "RULE_S04_ENTRY",
        "trigger": "sceneEnter",
        "support": "enforced",
        "description": "S04首次进入触发深潜者撤离与浓雾，并给出调查地图笔记的机会。",
        "when": {
          "sceneIs": "S04"
        },
        "effects": []
      },
      {
        "id": "RULE_S04_THUGS",
        "trigger": "sceneEnter",
        "support": "enforced",
        "description": "见过蒙特利尔且19:00后进入S04时触发暴徒伏击。",
        "when": {
          "all": [
            {
              "sceneIs": "S04"
            },
            {
              "variable": "metMontreal",
              "op": "eq",
              "value": true
            },
            {
              "worldTime": true,
              "op": "gte",
              "value": "1920-07-13T19:00"
            }
          ]
        },
        "effects": []
      },
      {
        "id": "RULE_HYBRID_SAN",
        "trigger": "sceneEnter",
        "support": "enforced",
        "description": "首次清楚目睹深潜者或浓雾咒术时，全队最低损失1点SAN。",
        "when": {
          "all": [
            {
              "sceneIs": "S04"
            },
            {
              "not": {
                "eventFired": "EV_S04_FOG"
              }
            }
          ]
        },
        "effects": []
      },
      {
        "id": "RULE_FUSANG_TIMER",
        "trigger": "clockTick",
        "support": "enforced",
        "description": "战斗路线第七轮结束时扶桑花号逃脱并进入结局B。",
        "when": {
          "clock": "fusangEscape",
          "op": "gte",
          "value": 7
        },
        "effects": [
          {
            "setEnding": "END_B"
          }
        ]
      },
      {
        "id": "RULE_LIGHT_COMBAT",
        "trigger": "combatStart",
        "support": "narrator_assisted",
        "description": "当前仅结构化敌方HP、击败数量和回合时钟；先攻、弹药与战术移动由Narrator辅助裁决。",
        "when": {
          "encounter": "ENC01",
          "state": "active"
        },
        "effects": []
      }
    ]
  },
  "presentation": {
    "openingNarrative": "1920年7月13日，英国伦敦。雨夜的伦敦裹在浓雾之中，煤气灯的光晕在水汽里渗散开来。你们站在纽伦上街101号的门廊下，手中握着伊莎贝拉·摩勒小姐的求助信。\n\n信中写道：「我父亲埃里克·摩勒于三日前失踪，警察局毫无进展。若您能找到他，必有重谢。」",
    "initialSuggestions": [
      "接受委托并询问失踪经过",
      "观察伊莎贝拉的状态",
      "要求查看埃里克的书房"
    ],
    "clocks": [
      {
        "id": "fusangEscape",
        "label": "扶桑花号离港",
        "max": 7
      }
    ],
    "caseBoard": {
      "summary": "围绕埃里克·摩勒失踪案，整理人物、地点、物证与待验证推测。",
      "nodes": [
        {
          "id": "scene-s01",
          "type": "scene",
          "refId": "S01",
          "title": "摩勒住宅",
          "subtitle": "委托起点",
          "importance": 5,
          "when": {
            "sceneVisited": "S01"
          }
        },
        {
          "id": "scene-s02",
          "type": "scene",
          "refId": "S02",
          "title": "上城区第二分局",
          "subtitle": "蒙特利尔任职的警局",
          "importance": 4,
          "when": {
            "sceneVisited": "S02"
          }
        },
        {
          "id": "scene-s03",
          "type": "scene",
          "refId": "S03",
          "title": "老赫特酒吧",
          "subtitle": "街区消息集散地",
          "importance": 4,
          "when": {
            "sceneVisited": "S03"
          }
        },
        {
          "id": "scene-s04",
          "type": "scene",
          "refId": "S04",
          "title": "卡森其药店",
          "subtitle": "贝尔街14号",
          "importance": 5,
          "when": {
            "any": [
              {
                "sceneVisited": "S04"
              },
              {
                "factKnown": "F06"
              },
              {
                "factKnown": "F08"
              }
            ]
          }
        },
        {
          "id": "scene-s05",
          "type": "scene",
          "refId": "S05",
          "title": "扶桑花号",
          "subtitle": "泰晤士港终幕地点",
          "importance": 5,
          "when": {
            "sceneVisited": "S05"
          }
        },
        {
          "id": "npc-isabella",
          "type": "npc",
          "refId": "N01",
          "title": "伊莎贝拉·摩勒",
          "subtitle": "委托人",
          "importance": 5,
          "when": {
            "sceneVisited": "S01"
          }
        },
        {
          "id": "npc-eric",
          "type": "npc",
          "refId": "N02",
          "title": "埃里克·摩勒",
          "subtitle": "失踪者",
          "importance": 5,
          "when": {
            "always": true
          }
        },
        {
          "id": "npc-montreal",
          "type": "npc",
          "refId": "N03",
          "title": "洛夫·蒙特利尔",
          "subtitle": "警察局长",
          "importance": 4,
          "when": {
            "factKnown": "F05"
          }
        },
        {
          "id": "npc-bartender",
          "type": "npc",
          "refId": "N04",
          "title": "老赫特之家酒保",
          "subtitle": "线人消息来源",
          "importance": 3,
          "when": {
            "sceneVisited": "S03"
          }
        },
        {
          "id": "npc-hybrid-envoy",
          "type": "npc",
          "refId": "N05",
          "title": "扶桑花号交涉代表",
          "subtitle": "终幕中的深潜者代表",
          "importance": 5,
          "when": {
            "sceneVisited": "S05"
          }
        },
        {
          "id": "item-i01",
          "type": "item",
          "refId": "I01",
          "title": "便签",
          "subtitle": "“别来找我”",
          "importance": 3,
          "when": {
            "any": [
              {
                "clue": "I01",
                "status": "discovered"
              },
              {
                "clue": "I01",
                "status": "analyzed"
              }
            ]
          }
        },
        {
          "id": "item-i02",
          "type": "item",
          "refId": "I02",
          "title": "合影照片",
          "subtitle": "蒙特利尔与埃里克",
          "importance": 4,
          "when": {
            "any": [
              {
                "clue": "I02",
                "status": "discovered"
              },
              {
                "clue": "I02",
                "status": "analyzed"
              }
            ]
          }
        },
        {
          "id": "item-i03",
          "type": "item",
          "refId": "I03",
          "title": "名片",
          "subtitle": "埃里克留下的旧公司地址",
          "importance": 3,
          "when": {
            "any": [
              {
                "clue": "I03",
                "status": "discovered"
              },
              {
                "clue": "I03",
                "status": "analyzed"
              }
            ]
          }
        },
        {
          "id": "item-i04",
          "type": "item",
          "refId": "I04",
          "title": "小册子",
          "subtitle": "夹页受过特殊处理",
          "importance": 5,
          "when": {
            "any": [
              {
                "clue": "I04",
                "status": "discovered"
              },
              {
                "clue": "I04",
                "status": "analyzed"
              }
            ]
          }
        },
        {
          "id": "item-i05",
          "type": "item",
          "refId": "I05",
          "title": "白色粉末样品",
          "subtitle": "车库暗格中的可疑粉末",
          "importance": 4,
          "when": {
            "any": [
              {
                "clue": "I05",
                "status": "discovered"
              },
              {
                "clue": "I05",
                "status": "analyzed"
              }
            ]
          }
        },
        {
          "id": "item-i06",
          "type": "item",
          "refId": "I06",
          "title": "报纸残片",
          "subtitle": "扫毒英雄通稿",
          "importance": 4,
          "when": {
            "any": [
              {
                "clue": "I06",
                "status": "discovered"
              },
              {
                "clue": "I06",
                "status": "analyzed"
              }
            ]
          }
        },
        {
          "id": "item-i07",
          "type": "item",
          "refId": "I07",
          "title": "深潜者地图笔记",
          "subtitle": "标注扶桑花号位置",
          "importance": 5,
          "when": {
            "any": [
              {
                "clue": "I07",
                "status": "discovered"
              },
              {
                "clue": "I07",
                "status": "analyzed"
              }
            ]
          }
        },
        {
          "id": "item-i08",
          "type": "item",
          "refId": "I08",
          "title": "雪茄头",
          "subtitle": "药店内收集的烟蒂",
          "importance": 4,
          "when": {
            "any": [
              {
                "clue": "I08",
                "status": "discovered"
              },
              {
                "clue": "I08",
                "status": "analyzed"
              }
            ]
          }
        },
        {
          "id": "theory-smuggling",
          "type": "theory",
          "refId": "F07",
          "title": "走私嫌疑",
          "subtitle": "失踪案背后可能有鸦片运输",
          "importance": 5,
          "when": {
            "factKnown": "F07"
          }
        },
        {
          "id": "theory-rat",
          "type": "theory",
          "refId": "F08",
          "title": "“老鼠”线索",
          "subtitle": "指向贝尔街14号",
          "importance": 3,
          "when": {
            "factKnown": "F08"
          }
        }
      ],
      "edges": [
        {
          "id": "CBE_01",
          "from": "scene-s01",
          "to": "npc-isabella",
          "label": "委托",
          "tone": "evidence",
          "when": {
            "always": true
          }
        },
        {
          "id": "s01-s02",
          "from": "scene-s01",
          "to": "scene-s02",
          "label": "调查路线",
          "tone": "route",
          "when": {
            "sceneVisited": "S02"
          }
        },
        {
          "id": "s01-s03",
          "from": "scene-s01",
          "to": "scene-s03",
          "label": "调查路线",
          "tone": "route",
          "when": {
            "sceneVisited": "S03"
          }
        },
        {
          "id": "s02-montreal",
          "from": "scene-s02",
          "to": "npc-montreal",
          "label": "任职于此",
          "tone": "evidence",
          "when": {
            "sceneVisited": "S02"
          }
        },
        {
          "id": "s03-bartender",
          "from": "scene-s03",
          "to": "npc-bartender",
          "label": "在场",
          "tone": "evidence",
          "when": {
            "sceneVisited": "S03"
          }
        },
        {
          "id": "s03-s04",
          "from": "scene-s03",
          "to": "scene-s04",
          "label": "贝尔街线索",
          "tone": "route",
          "when": {
            "factKnown": "F08"
          }
        },
        {
          "id": "CBE_02",
          "from": "item-i02",
          "to": "npc-montreal",
          "label": "关系异常",
          "tone": "suspicion",
          "when": {
            "factKnown": "F05"
          }
        },
        {
          "id": "photo-eric",
          "from": "item-i02",
          "to": "npc-eric",
          "label": "同框",
          "tone": "evidence",
          "when": {
            "factKnown": "F05"
          }
        },
        {
          "id": "powder-smuggling",
          "from": "item-i05",
          "to": "theory-smuggling",
          "label": "指向走私",
          "tone": "danger",
          "when": {
            "factKnown": "F07"
          }
        },
        {
          "id": "paper-smuggling",
          "from": "item-i06",
          "to": "theory-smuggling",
          "label": "形成证据压力",
          "tone": "suspicion",
          "when": {
            "clue": "I06",
            "status": "discovered"
          }
        },
        {
          "id": "smuggling-eric",
          "from": "theory-smuggling",
          "to": "npc-eric",
          "label": "并非单纯受害者",
          "tone": "danger",
          "when": {
            "factKnown": "F01"
          }
        },
        {
          "id": "CBE_03",
          "from": "item-i04",
          "to": "scene-s04",
          "label": "指向地址",
          "tone": "route",
          "when": {
            "factKnown": "F06"
          }
        },
        {
          "id": "CBE_04",
          "from": "npc-bartender",
          "to": "theory-rat",
          "label": "提供情报",
          "tone": "evidence",
          "when": {
            "factKnown": "F08"
          }
        },
        {
          "id": "CBE_05",
          "from": "theory-rat",
          "to": "scene-s04",
          "label": "贝尔街方向",
          "tone": "route",
          "when": {
            "factKnown": "F08"
          }
        },
        {
          "id": "CBE_06",
          "from": "item-i07",
          "to": "scene-s05",
          "label": "定位扶桑花号",
          "tone": "route",
          "when": {
            "factKnown": "F09"
          }
        },
        {
          "id": "CBE_07",
          "from": "item-i08",
          "to": "npc-eric",
          "label": "近期到过药店",
          "tone": "evidence",
          "when": {
            "factKnown": "F10"
          }
        },
        {
          "id": "CBE_08",
          "from": "scene-s05",
          "to": "npc-hybrid-envoy",
          "label": "守在船上",
          "tone": "danger",
          "when": {
            "sceneVisited": "S05"
          }
        },
        {
          "id": "CBE_09",
          "from": "npc-hybrid-envoy",
          "to": "npc-eric",
          "label": "扣押",
          "tone": "danger",
          "when": {
            "factKnown": "F01"
          }
        }
      ]
    }
  }
} as ScenarioModule;
